### ISSUE TITLE
Testing Asynchronous Methods: TypeError: (0 , _.ChatMessageService) is not a function

### ISSUE THREAD

**Issue by angela-mitchell-vmlyr** [danielstern/vue-jest#5]
**Issue**

I attempted to run the following lines of code in `chatMessageService.spec.js`:

```
import { ChatMessageService } from './';

describe("the message service",() => {

    let chatMessageService;

    beforeEach(()=>{
        
        chatMessageService = ChatMessageService([]);

    });


    it("should add messages", () => {

        expect(chatMessageService.getMessages()).toHaveLength(0);
    
    });
});
```

When running the test, I received the following results:

```
 FAIL  src/services/chatMessageService/chatMessageService.spec.js
  ● the message service › should add messages

    TypeError: (0 , _.ChatMessageService) is not a function

       7 |     beforeEach(()=>{
       8 |         
    >  9 |         chatMessageService = ChatMessageService([]);
         |                              ^
      10 | 
      11 |     });
      12 | 

      at Object.<anonymous> (src/services/chatMessageService/chatMessageService.spec.js:9:30)

  ● the message service › should add messages

    TypeError: Cannot read property 'getMessages' of undefined

      14 |     it("should add messages", () => {
      15 | 
    > 16 |         expect(chatMessageService.getMessages()).toHaveLength(0);
         |                                   ^
      17 |     
      18 |     });
      19 | });

      at Object.<anonymous> (src/services/chatMessageService/chatMessageService.spec.js:16:35)

 PASS  src/routes/Chat/Chat.spec.js
```

I checked my `index.js` file to verify that the `getMessages()` property exists there. I also compared what I have for the associated files to my current ones. It looks like everything is matching. Is there an importing issue with Jest that has a fix available for this?

**Resolution**

I see that there are some differences in the video in the `index.js` file. This file should look like this for the appropriate Jest test results to print to the console:

```
import { v4 } from 'uuid';

const _messages = [{

    id: v4(),
    sender:"M",
    content: "Hello. This is customer support."

},{

    id: v4(),
    sender:"M",
    content: "How can we assist you today?"
    
}];

export const ChatMessageService = (messages = _messages) => ({
    async getMessages(){
        
        return messages;

    },
    async submitMessage({sender, content}){

        messages.push({
            sender,
            content,
            id: v4()
        })

    },
    subscribe(){
        
        return function*(){

            console.log("You subscribed");
            
        }

    }
});
```

**Comment by danielstern** [comment]
What is the read out of console.log(ChatMessageService)?
________________________________
From: Angela Mitchell ***@***.***>
Sent: July 31, 2021 8:41 PM
To: danielstern/vue-jest ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [danielstern/vue-jest] Testing Asynchronous Methods: TypeError: (0 , _.ChatMessageService) is not a function (#5)


Issue

I attempted to run the following lines of code in chatMessageService.spec.js:

import { ChatMessageService } from './';



describe("the message service",() => {



    let chatMessageService;



    beforeEach(()=>{



        chatMessageService = ChatMessageService([]);



    });





    it("should add messages", () => {



        expect(chatMessageService.getMessages()).toHaveLength(0);



    });

});



When running the test, I received the following results:

 FAIL  src/services/chatMessageService/chatMessageService.spec.js

  ● the message service › should add messages



    TypeError: (0 , _.ChatMessageService) is not a function



       7 |     beforeEach(()=>{

       8 |

    >  9 |         chatMessageService = ChatMessageService([]);

         |                              ^

      10 |

      11 |     });

      12 |



      at Object.<anonymous> (src/services/chatMessageService/chatMessageService.spec.js:9:30)



  ● the message service › should add messages



    TypeError: Cannot read property 'getMessages' of undefined



      14 |     it("should add messages", () => {

      15 |

    > 16 |         expect(chatMessageService.getMessages()).toHaveLength(0);

         |                                   ^

      17 |

      18 |     });

      19 | });



      at Object.<anonymous> (src/services/chatMessageService/chatMessageService.spec.js:16:35)



 PASS  src/routes/Chat/Chat.spec.js



I checked my index.js file to verify that the getMessages() property exists there. I also compared what I have for the associated files to my current ones. It looks like everything is matching. Is there an importing issue with Jest that has a fix available for this?

**Comment by angela-mitchell-vmlyr** [comment]
@danielstern  With the code I added from the video for the `index.js` file in the `services/chatMessageService` directory, `console.log(ChatMessageService)` returns the following in the browser dev tools:

```
ChatMessageService() {
  var messages = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : _messages;
  return {
    getMessages: function getMessages() {
      return _babel_runtime…
```

There are errors that follow it, but I think I must be missing something from the video or it may get resolved once I work on the final section of the course:

```
[Vue warn]: Error in mounted hook (Promise/async): "TypeError: _services_chatMessageService_index_js__WEBPACK_IMPORTED_MODULE_3__.ChatMessageService.getMessages is not a function"

found in

---> <App> at src/App.vue
       <Root>
```

```
TypeError: _services_chatMessageService_index_js__WEBPACK_IMPORTED_MODULE_3__.ChatMessageService.getMessages is not a function
    at _callee$ (App.vue?./node_modules/babel-loader/lib??ref--1!./node_modules/vue-loader/lib??vue-loader-options:42)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.eval [as next] (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at eval (asyncToGenerator.js:32)
    at new Promise (<anonymous>)
    at eval (asyncToGenerator.js:21)
    at VueComponent.mounted (App.vue?./node_modules/babel-loader/lib??ref--1!./node_modules/vue-loader/lib??vue-loader-options:55)
```

The tests seem be working as expected now, though.

**Comment by gleekzorp** [comment]
I ran into the same issue.  Updating the `chatMessageService/index.js` with the code in @angela-mitchell-vmlyr Resolution section fixed it for me.

**Comment by danielstern** [comment]
Feel free to submit a PR
________________________________
